# create configmap for cwagent config
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          
          "kubernetes": {
            "metrics_collection_interval": 30
          }
        },
        "force_flush_interval": 5
      },
      
      "metrics": {
        "metrics_collected": {
            "statsd": {
                "service_address": ":8080"
            }
        }
    }
    }
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
